version: '3'
services:
  gateway:
    build: ./gateway
    restart: always
    hostname: gateway
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - backend
      - frontend
  route:
    build: ./route
    restart: always
    hostname: route
    env_file:
      - .env
    networks:
      - backend
    links:
      - db-pg
  token:
    build: ./token
    restart: always
    hostname: token
    env_file:
      - .env
    networks:
      - backend
    links:
      - db-mongo
  ticket:
    build: ./ticket
    restart: always
    hostname: ticket
    env_file:
      - .env
    networks:
      - backend
    links:
      - db-mongo
  permission:
    build: ./permission
    restart: always
    hostname: permission
    env_file:
      - .env
    networks:
      - backend
  user:
    build: ./user
    restart: always
    hostname: user
    env_file:
      - .env
    networks:
      - backend
    links:
      - ticket
      - db-mongo
  db-mongo:
    image: 'mongo:3.7'
    hostname: db-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - "./db-dumb/data/db-files:/data/db"
      - "./db-dumb/init/:/docker-entrypoint-initdb.d/"
    ports:
      - 27017:27017
    networks:
      - backend
  db-pg:
    image: 'postgres:14.5-bullseye'
    restart: always
    hostname: db-pg
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/posgresql/data
      - ./db-dumb/route/test/e2e-setup/e2e-init-db.sql:/docker-entrypoint-initdb.d/e2e-init-db.sql
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - backend
networks:
  backend:
    driver: bridge
  frontend:
    external:
      name: infrastructure
volumes:
  postgres-data:
