version: '3'

services:
  db:
    image: postgres:14.5-bullseye
    container_name: tpj-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/posgresql/data
      - ./test/e2e-setup/e2e-init-db.sql:/docker-entrypoint-initdb.d/e2e-init-db.sql

  cache:
    image: redis/redis-stack-server:7.0.6-RC4
    container_name: tpj-redis
    command:
      [
        'redis-server',
        '--loadmodule /opt/redis-stack/lib/rejson.so',
        '--protected-mode no',
      ]
    restart: always
    ports:
      - ${REDIS_PORT}:6379

volumes:
  postgres-data:
