apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-week-09-1008
  name: java-service
  namespace: group-2-dev
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 80
  selector:
    app: java-week-09-1008
status:
  loadBalancer: {}
